# Generated by Django 4.1 on 2024-05-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_review_rname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rname",
            field=models.CharField(max_length=250),
        ),
    ]
