# Generated by Django 4.1 on 2024-05-29 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_review_rname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rname",
        ),
    ]
