# Generated by Django 4.1 on 2024-05-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_review_user_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movies.category",
            ),
        ),
    ]
